# This is the application controller
# Any functionality needed across all controllers

# This was generated by Rails. Should not be edited by developers
class ApplicationController < ActionController::Base
end
