default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  timeout: 5000
  encoding: unicode
  template: template0

development:
  <<: *default
  database: open_learning_platform

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
  encoding: unicode
